Repository thoth-station/meteor-operator, pull requests merged in 2021-08, with the labels that each got.

#2 attach pipeline resource for git repo
  controllers/pipelinerun_reconciler.go
Labels: size/S

#1 Better logging and unified code flow
  .pre-commit-config.yaml
  api/v1alpha1/meteor_types.go
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/meteor.operate-first.cloud_meteors.yaml
  config/samples/meteor_v1alpha1_meteor.yaml
  controllers/constants.go
  controllers/deployment_reconciler.go
  controllers/imagestream_reconciler.go
  controllers/meteor_controller.go
  controllers/pipelinerun_reconciler.go
  controllers/route_reconciler.go
  controllers/service_reconciler.go
  controllers/utils.go
  yamllint-config.yaml
Labels: approved, size/L

#6 openshift pipelines which will take care of meteor
  config/pipelines/build-check.yaml
  config/pipelines/config.yaml
  config/pipelines/jupyterbook-build.yaml
  config/pipelines/jupyterbook.yaml
  config/pipelines/jupyterhub.yaml
  config/pipelines/kustomization.yaml
  config/pipelines/notebook-build.yaml
  config/pipelines/rbac.yaml
Labels: size/XL

#5 include the pushgateway for metrics export
  config/pushgateway/configmap.yaml
  config/pushgateway/kustomization.yaml
  config/pushgateway/pushgateway.yaml
Labels: approved, size/M, lgtm

#4 feat: Enable cluster roles for edit/view
  config/rbac/kustomization.yaml
  config/rbac/meteor_editor_role.yaml
  config/rbac/meteor_viewer_role.yaml
Labels: size/XS, lgtm

#7 feat: Remove webhook and aggregate status
  .vscode/launch.json
  PROJECT
  README.md
  api/v1alpha1/meteor_types.go
  api/v1alpha1/meteor_webhook.go
  api/v1alpha1/webhook_suite_test.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/meteor.operate-first.cloud_meteors.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/meteor_controller.go
  main.go
Labels: approved

#9 feat: Add expirationTimestamp
  api/v1alpha1/meteor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.operate-first.cloud_meteors.yaml
  controllers/meteor_controller.go
Labels: approved, size/S, lgtm

#13 feat: Create K8S resources via Tekton instead of in operator
  config/manager/kustomization.yaml
  config/pipelines/kustomization.yaml
  config/pipelines/pipelines/jupyterbook.yaml
  config/pipelines/pipelines/jupyterhub.yaml
  config/pipelines/role.yaml
  controllers/deployment_reconciler.go
  controllers/imagestream_reconciler.go
  controllers/meteor_controller.go
  controllers/route_reconciler.go
  controllers/service_reconciler.go
Labels: size/XL, approved, lgtm

#16 Collect results
  api/v1alpha1/meteor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.operate-first.cloud_meteors.yaml
  config/pipelines/pipelines/jupyterbook.yaml
  config/pipelines/pipelines/jupyterhub.yaml
  config/pipelines/role.yaml
  config/pipelines/tasks/kustomization.yaml
  config/pipelines/tasks/oc-actions.yaml
  controllers/meteor_controller.go
  controllers/pipelinerun_reconciler.go
Labels: approved, size/L, lgtm

#25 Cross namespace garbage collection
  PROJECT
  api/v1alpha1/meteor_types.go
  api/v1alpha1/meteorcoma_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.operate-first.cloud_meteorcomas.yaml
  config/crd/bases/meteor.operate-first.cloud_meteors.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_meteorcomas.yaml
  config/crd/patches/webhook_in_meteorcomas.yaml
  config/pipelines/pipelines/jupyterbook.yaml
  config/pipelines/pipelines/jupyterhub.yaml
  config/pipelines/role.yaml
  config/pipelines/tasks/kustomization.yaml
  config/pipelines/tasks/resolve-owner-reference.yaml
  config/rbac/meteorcoma_editor_role.yaml
  config/rbac/meteorcoma_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/meteor_v1alpha1_meteorcoma.yaml
  controllers/coma_reconciler.go
  controllers/constants.go
  controllers/meteor_controller.go
  controllers/pipelinerun_reconciler.go
Labels: size/XL

#26 fix: Keep base image tag preference
  config/pipelines/tasks/generate-jupyterhub.yaml
Labels: lgtm
