Repository thoth-station/meteor-operator, pull requests merged in 2021-11, with the labels that each got.

#44 fix: resource tab in OLM
  api/v1alpha1/meteor_types.go
  bundle/manifests/meteor-operator.clusterserviceversion.yaml
  config/manifests/bases/meteor-operator.clusterserviceversion.yaml
Labels: approved, size/S, lgtm

#46 Rename apigroup
  PROJECT
  README.md
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/meteor_types.go
  bundle/manifests/meteor-operator-manager-config_v1_configmap.yaml
  bundle/manifests/meteor-operator-meteor-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/meteor-operator-meteor-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/meteor-operator.clusterserviceversion.yaml
  bundle/manifests/meteor.zone_meteorcomas.yaml
  bundle/manifests/meteor.zone_meteors.yaml
  config/crd/bases/meteor.zone_meteorcomas.yaml
  config/crd/bases/meteor.zone_meteors.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_meteorcomas.yaml
  config/crd/patches/cainjection_in_meteors.yaml
  config/crd/patches/webhook_in_meteorcomas.yaml
  config/crd/patches/webhook_in_meteors.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/meteor-operator.clusterserviceversion.yaml
  config/pipelines/role.yaml
  config/rbac/meteor_editor_role.yaml
  config/rbac/meteor_viewer_role.yaml
  config/rbac/meteorcoma_editor_role.yaml
  config/rbac/meteorcoma_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/meteor_v1alpha1_meteor.yaml
  controllers/constants.go
  controllers/meteor_controller.go
  main.go
Labels: approved, size/L, lgtm

#45 wip: feat: Make TTL optional
  api/v1alpha1/meteor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/meteor.operate-first.cloud_meteors.yaml
  config/crd/bases/meteor.operate-first.cloud_meteors.yaml
  controllers/meteor_controller.go
Labels: do-not-merge/hold, do-not-merge/work-in-progress, size/S

#47 write image_url to the results for tekton chains signature
  config/pipelines/tasks/buildah.yaml
Labels: size/XS, approved, lgtm

#49 Add shower
  Dockerfile
  PROJECT
  api/v1alpha1/shower_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.zone_showers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_showers.yaml
  config/crd/patches/webhook_in_showers.yaml
  config/pipelines/role.yaml
  config/rbac/role.yaml
  config/rbac/shower_editor_role.yaml
  config/rbac/shower_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/meteor_v1alpha1_shower.yaml
  controllers/common/metrics.go
  controllers/constants.go
  controllers/meteor/coma_reconciler.go
  controllers/meteor/meteor_controller.go
  controllers/meteor/pipelinerun_reconciler.go
  controllers/shower/deployment_reconciler.go
  controllers/shower/role_reconciler.go
  controllers/shower/rolebinding_reconciler.go
  controllers/shower/route_reconciler.go
  controllers/shower/service_reconciler.go
  controllers/shower/serviceaccount_reconciler.go
  controllers/shower/servicemonitor_reconciler.go
  controllers/shower/shower_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  version/version.go
Labels: approved, size/XXL, lgtm

#50 Pass params to pipeline
  api/v1alpha1/shower_types.go
  config/crd/bases/meteor.zone_showers.yaml
  controllers/meteor/meteor_controller.go
  controllers/meteor/pipelinerun_reconciler.go
  controllers/shower/shower_controller.go
Labels: approved, size/M, lgtm

#54 feat: Rename MeteorComa to Coma
  Makefile
  PROJECT
  api/v1alpha1/coma_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/meteor-operator.clusterserviceversion.yaml
  bundle/manifests/meteor.zone_comas.yaml
  bundle/manifests/meteor.zone_showers.yaml
  config/crd/bases/meteor.zone_comas.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_comas.yaml
  config/crd/patches/webhook_in_comas.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/meteor-operator.clusterserviceversion.yaml
  config/rbac/coma_editor_role.yaml
  config/rbac/coma_viewer_role.yaml
  config/rbac/role.yaml
  controllers/meteor/coma_reconciler.go
  controllers/meteor/meteor_controller.go
  controllers/shower/role_reconciler.go
Labels: size/XL, approved, lgtm
