Repository thoth-station/meteor-operator, pull requests merged in 2022-10, with the labels that each got.

#105 Add changes from the spike-cnbi-crd branch
  api/v1alpha1/customnbimage_types.go
  api/v1alpha1/customnbimage_types_test.go
  api/v1alpha1/customnbimage_webhook.go
  api/v1alpha1/customnbimage_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.zone_customnbimages.yaml
  controllers/customnbimage_controller.go
  controllers/customnbimage_controller_test.go
Labels: approved, size/L, lgtm

#104 Use the custom configmap for controller deployment
  config/base/kustomization.yaml
Labels: approved, size/M

#109 Add aicoe-ci configuration to build the image
  .aicoe-ci.yaml
Labels: approved, size/S, lgtm

#112 Add docs to install-pipelines target + simplify
  Makefile
Labels: approved, size/S, lgtm

#113 Check kind cluster existence as part of recipe
  Makefile
Labels: approved, size/S, lgtm
