Repository thoth-station/meteor-operator, pull requests merged in 2022-11, with the labels that each got.

#116 Simplify Makefile
  Makefile
Labels: approved, size/L, lgtm

#117 Fix typo in makefile following #116
  Makefile
Labels: size/XS, approved, lgtm

#114 Base version on 'git describe --tags'
  Makefile
Labels: size/XS, approved, lgtm

#119 :bug: remove 'v' from VERSION, as our tags do contain it
  Makefile
Labels: size/XS, approved, lgtm

#120 add prow job to run `make test`
  .prow.yaml
Labels: size/S

#125 Use the full image name for the golang image
  Dockerfile
Labels: size/XS, approved, lgtm

#110 import from private registry (Condition work)
  Makefile
  api/v1alpha1/cnbi_condition_consts.go
  api/v1alpha1/cnbi_condition_types.go
  api/v1alpha1/common.go
  api/v1alpha1/customnbimage_types.go
  api/v1alpha1/customnbimage_types_test.go
  api/v1alpha1/meteor_types.go
  api/v1alpha1/shower_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.zone_customnbimages.yaml
  config/samples/meteor_v1alpha1_customnbimage.yaml
  config/samples/meteor_v1alpha1_customnbimage_import_only.yaml
  controllers/cnbi/conditions.go
  controllers/cnbi/conditions_test.go
  controllers/cnbi/controller.go
  controllers/cnbi/controller_test.go
  controllers/cnbi/suite_test.go
  controllers/meteor/meteor_controller.go
  controllers/shower/shower_controller.go
  go.mod
  main.go
Labels: approved, size/XXL, lgtm

#127 Test that cnbi maintain a correct state
  controllers/cnbi/controller_test.go
Labels: size/S

#132 Do not include 'dirty' in image version
  Makefile
Labels: size/XS, approved, lgtm

#133 add config for golangci-lint
  .golangci.yaml
Labels: approved, size/S, lgtm

#131 Ignore generated files in diff
  .gitattributes
Labels: approved, size/S, lgtm

#138 OWNERS cleanup pt. 2
  OWNERS
Labels: size/XS

#129 Refactor cnbi reconcile loop and conditions
  api/v1alpha1/cnbi_condition_consts.go
  api/v1alpha1/cnbi_condition_types.go
  api/v1alpha1/customnbimage_types.go
  api/v1alpha1/customnbimage_types_test.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.zone_customnbimages.yaml
  controllers/cnbi/conditions.go
  controllers/cnbi/conditions_test.go
  controllers/cnbi/controller.go
  controllers/cnbi/controller_const.go
Labels: size/XL, approved, lgtm

#108 Include pipelines with operator for easy install
  pipelines/base/kustomization.yaml
  pipelines/base/role.yaml
  pipelines/pipelines/cnbi-gitrepo.yaml
  pipelines/pipelines/cnbi-import.yaml
  pipelines/pipelines/kustomization.yaml
  pipelines/tasks/extract-external-service.yaml
  pipelines/tasks/generate-jupyterhub.yaml
  pipelines/tasks/kustomization.yaml
  pipelines/tasks/resolve-owner-reference.yaml
  pipelines/tasks/validate-jupyterhub-image.yaml
Labels: size/XL, approved, lgtm

#141 Split CNBi samples object into one file per object
  config/samples/meteor_v1alpha1_customnbimage.yaml
  config/samples/meteor_v1alpha1_customnbimage_git-repository.yaml
  config/samples/meteor_v1alpha1_customnbimage_image-import.yaml
  config/samples/meteor_v1alpha1_customnbimage_package-list-1.yaml
  config/samples/meteor_v1alpha1_customnbimage_package-list-2.yaml
  config/samples/meteor_v1alpha1_customnbimage_package-list-3.yaml
Labels: approved, size/L, lgtm

#144 fix/kustomization yaml no generated
  .gitattributes
  config/.gitattributes
Labels: approved, size/S, lgtm

#143 fix/makefile install pipelines
  Makefile
  hack/cnbi-gitrepo.yaml
  hack/cnbi-import.yaml
  hack/cnbi-prepare.yaml
  pipelines/base/kustomization.yaml
  pipelines/base/role.yaml
Labels: approved, size/XXL, lgtm

#134 Use Subscription object to install pre-requisisites (Pipelines, Cert manager)
  Makefile
Labels: approved, size/M, lgtm

#146 Add nfs provisioner script
  README.md
  script_nfs.bash
Labels: approved, size/M, lgtm

#148 Upgrade openshift-pipelines version to 1.8.*
  Makefile
Labels: size/XS, approved, lgtm

#106 PackageList pipeline
  pipelines/pipelines/cnbi-package-list.yaml
  pipelines/pipelines/kustomization.yaml
  pipelines/tasks/buildah-requirements.yaml
  pipelines/tasks/get-package-versions-list.yaml
  pipelines/tasks/kustomization.yaml
Labels: approved, size/L, lgtm

#147 Add 'Age' to the printed column
  api/v1alpha1/customnbimage_types.go
  config/crd/bases/meteor.zone_customnbimages.yaml
Labels: size/XS, approved, lgtm

#139 Rename cnbi to cre
  Makefile
  OWNERS
  PROJECT
  README.md
  Tiltfile
  api/v1alpha1/common.go
  api/v1alpha1/cre_condition_consts.go
  api/v1alpha1/customnbimage_webhook_test.go
  api/v1alpha1/customruntimeenvironment_types.go
  api/v1alpha1/customruntimeenvironment_types_test.go
  api/v1alpha1/customruntimeenvironment_webhook.go
  api/v1alpha1/customruntimeenvironment_webhook_test.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.zone_customruntimeenvironments.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_customruntimeenvironments.yaml
  config/crd/patches/webhook_in_customruntimeenvironments.yaml
  config/rbac/customruntimeenvironment_editor_role.yaml
  config/rbac/customruntimeenvironment_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/meteor_v1alpha1_customruntimeenvironment_git-repository.yaml
  config/samples/meteor_v1alpha1_customruntimeenvironment_image-import.yaml
  config/samples/meteor_v1alpha1_customruntimeenvironment_import_only.yaml
  config/samples/meteor_v1alpha1_customruntimeenvironment_package-list-1.yaml
  config/samples/meteor_v1alpha1_customruntimeenvironment_package-list-2.yaml
  config/samples/meteor_v1alpha1_customruntimeenvironment_package-list-3.yaml
  config/webhook/manifests.yaml
  controllers/cre/controller.go
  controllers/cre/controller_const.go
  controllers/cre/controller_test.go
  controllers/cre/suite_test.go
  main.go
  pipelines/pipelines/cre-gitrepo.yaml
  pipelines/pipelines/cre-import.yaml
  pipelines/pipelines/cre-package-list.yaml
  pipelines/pipelines/kustomization.yaml
  pipelines/tasks/buildah-requirements.yaml
Labels: size/XL, approved, lgtm

#151 Fix import pipeline parameter names and validate task reference
  pipelines/pipelines/cre-import.yaml
  pipelines/tasks/validate-jupyterhub-image.yaml
Labels: approved, size/M, lgtm
