Repository thoth-station/meteor-operator, pull requests merged in 2022-12, with the labels that each got.

#154 Update the controller version tag to match the current version
  Tiltfile
  config/manager/kustomization.yaml
  config/manifests/bases/meteor-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, size/S, lgtm

#158 introducte PackageListBuildCompleted condition
  api/v1alpha1/cre_condition_consts.go
  api/v1alpha1/customruntimeenvironment_types.go
  api/v1alpha1/customruntimeenvironment_types_test.go
  controllers/cre/controller.go
Labels: approved, size/M, lgtm

#153 :arrow_up: update pre-commit hook versions
  .pre-commit-config.yaml
Labels: size/XS, approved, lgtm

#160 Fix label and annotation handling in the import pipeline
  pipelines/pipelines/cre-import.yaml
Labels: approved, size/S, lgtm
