Repository thoth-station/meteor-operator, pull requests merged in 2022-09, with the labels that each got.

#63 operator sdk update
  .pre-commit-config.yaml
  .prow.yaml
  Dockerfile
  Makefile
  README.md
  config/crd/bases/meteor.zone_comas.yaml
  config/crd/bases/meteor.zone_meteors.yaml
  config/crd/bases/meteor.zone_showers.yaml
  config/rbac/role.yaml
  controllers/meteor/pipelinerun_reconciler.go
  go.mod
  go.sum
Labels: approved, size/XXL, lgtm

#67 Validating Webhooks
  .gitignore
  Makefile
  PROJECT
  README.md
  api/v1alpha1/customnbimage_types.go
  api/v1alpha1/customnbimage_types_test.go
  api/v1alpha1/customnbimage_webhook.go
  api/v1alpha1/customnbimage_webhook_test.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/meteorconfig_types.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/meteor-operator.clusterserviceversion.yaml
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/crd/test/tekton-pipeline-v0.39.0.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/samples/meteor_v1alpha1_customnbimage.yaml
  config/samples/meteor_v1alpha1_meteorconfig.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/customnbimage_controller.go
  controllers/customnbimage_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, size/XXL, lgtm

#73 Rename aicoe-meteor to meteor-system
  Makefile
  README.md
  config/default/kustomization.yaml
  config/olm/operatorgroup.yaml
Labels: approved, size/M, lgtm

#71 Refactor CRD to latest discussion on hackmd
  Makefile
  README.md
  api/v1alpha1/customnbimage_types.go
  api/v1alpha1/customnbimage_webhook.go
  api/v1alpha1/customnbimage_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/meteor.zone_customnbimages.yaml
  config/default/kustomization.yaml
  config/samples/meteor_v1alpha1_customnbimage.yaml
  controllers/customnbimage_controller.go
  controllers/customnbimage_controller_test.go
  hack/kind-config.yaml
  main.go
Labels: approved, size/L, lgtm

#75 Add microshift instructions
  README.md
Labels: approved, size/M, lgtm

#78 fix typo in makefile target mentioned
  README.md
Labels: size/XS, approved, lgtm

#79 Add a pipeline to implement the GitRepository build type
  Makefile
  api/v1alpha1/customnbimage_types.go
  config/crd/bases/meteor.zone_customnbimages.yaml
  config/samples/meteor_v1alpha1_customnbimage.yaml
  controllers/customnbimage_controller.go
  hack/cnbi-gitrepo.yaml
  hack/cnbi-import.yaml
  hack/cnbi-validate-task.yaml
Labels: approved, size/XXL, lgtm

#83 put all the container images in thoth-station org on quay
  Makefile
  bundle/manifests/meteor-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: approved, size/XXL, lgtm

#81 rename namespace set from deployment
  config/default/kustomization.yaml
Labels: size/XS, approved, lgtm

#85 Hack to allow deployment from a KfDef
  config/base
Labels: size/XS, approved, lgtm

#86 Testing modifications
  config/default/deleteme.txt
Labels: size/XS, lgtm

#87 Updated hack for KfDef
  config/base
  config/base/kustomization.yaml
  config/base/manager_auth_proxy_patch.yaml
  config/base/manager_config_patch.yaml
  config/base/manager_insecure_patch.yaml
  config/base/manager_webhook_patch.yaml
  config/base/webhookcainjection_patch.yaml
  config/default
  config/default/deleteme.txt
Labels: size/XS, lgtm

#93 :bomb: remove .vscode/
  .gitignore
  .vscode/launch.json
Labels: approved, size/S

#96 add a "cnbi" shortname for CustomNBImage
  README.md
  api/v1alpha1/customnbimage_types.go
  config/crd/bases/meteor.zone_customnbimages.yaml
Labels: approved, size/S
