Repository thoth-station/meteor-operator, pull requests merged in 2023-01, with the labels that each got.

#156 Fixes for the NFS provisioner helper script
  hack/script_nfs.bash
Labels: approved, size/S, lgtm

#166 Add myself as approver + reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#164 just renamed condition_const of CRE
  api/v1alpha1/customruntimeenvironment_condition_consts.go
Labels: size/XS, approved, lgtm

#165 Use pipeline CRD directly from tekton-pipeline
  config/crd/test/tekton-pipeline-v0.39.0.yaml
  controllers/cre/suite_test.go
Labels: size/XL, approved, kind/cleanup, lgtm

#161 change tekton pipeline metadata to generatename
  controllers/cre/controller.go
Labels: size/XS, approved, lgtm
